services:
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage-s3
    restart: unless-stopped
    ports:
      - "3900:3900"   # S3 API port
    volumes:
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
      - ./config/garage.toml:/etc/garage.toml:ro
    environment:
      - TZ=Europe/London
